image: rocker/tidyverse

stages:
  - test
  - deploy

# To have the converage percentge appear as a gitlab badge follow these instructions
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Code coverage: \d+\.\d+

testing:
    stage: test
    allow_failure: true
    when: on_success
    script:
        - sudo apt-get install --yes qpdf
        - R -e "remotes::install_deps()"
        - R -e 'devtools::check()'
        - R -e 'install.packages("DT")'
        - R -e 'covr::gitlab(quiet = FALSE)'
    artifacts:
        paths:
            - public

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

pages:
    stage: deploy
    dependencies:
        - testing
    script:
        - ls
    artifacts:
        paths:
            - public
        expire_in: 30 days